name: The Eblen Team
favicon: null
layout_spectrum: 1
typography_spectrum: 0.59635
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a7cf38'
    - '#f5821f'
    - '#cd1f30'
    - '#009dae'
  brandStrength: 1
  lightness: 0.46736705116927624
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
